- hosts: all
  become: yes
  strategy: free

  # vars_files:
  #   - scripts/vars.yml
  roles:



  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common 
        - gnupg2
        - net-tools
        - python3-minimal 
        - build-essential 
        - python3-pip
    - name: General Python dependencies
      pip:
        name:  
        - ansible
        - setuptools
        - docker-py
        # k8s_module 
        - openshift >= 0.6
        - PyYAML >= 3.11



- import_playbook: "../../ansible/init.yml"
# - import_playbook: "../../ansible/rancher.yml"
# - import_playbook: ../../ansible/k3s-workarounds-playbook.yml

# - import_playbook: playbooks/helm-playbook.yml
#   when: install_helm is defined and install_helm

# Disabled until rancher ui works on k3s 
# Requires install_rancher: true in vars.yml if activated later
#- import_playbook: playbooks/rancher-playbook.yml
#  when: install_rancher is defined and install_rancher