# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| 
    config.vm.box = "ubuntu/focal64"
    config.vm.network "forwarded_port", guest: 443, host: 8443
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder "../ansible", "/opt/ansible"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 2
      vb.name = "POC-k3s"
    end
    config.vm.provision "shell", path: "scripts/ansible-installer.sh"
    config.vm.provision "shell", path: "scripts/run-playbooks.sh"
  end
  