---
  - hosts: all, localhost
    become: yes
    environment:
      INSTALL_K3S_VERSION: "{{ k3s_version }}"
    vars_files:
      - ./vars/variables.yml
    tasks:
      - name: Create Ansible directory structure
        file:
          path: /opt/ansible/files/generated
          state: directory
          mode: '0755'
      - name: Installing fail2ban
        apt:
          name: fail2ban
          update_cache: yes
          state: latest
      - name: Copy fail2ban config
        copy:
          src: ./files/jail.local
          dest: /etc/fail2ban/jail.local
      - name: Enable fail2ban
        systemd:
          name: fail2ban
          enabled: yes
          state: started
      - name: Install Docker
        shell: curl https://releases.rancher.com/install-docker/19.03.sh | sh
        when: use_docker
      - name: Install K3s for Docker
        shell:  curl -sfL https://get.k3s.io | sh -s - --docker
        when: use_docker
      - name: Install K3s with containerd
        shell: curl -sfL https://get.k3s.io | sh -
        when: not use_docker
      - name: Get Helm Installer
        get_url: 
          url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          dest: ~/get-helm-3
          mode: 330
      - name: Install Helm
        shell: ~/get-helm-3
      # - name: Add NextCloud helm repo
      #   kubernetes.core.helm_repository:
      #     name: nextcloud
      #     repo_url: https://nextcloud.github.io/helm/

